version: '3.8'

services:
  app:
    container_name: app
    build: ./app/ # local source for backend
    depends_on:
      # build ollama before app
      ollama:
        condition: service_healthy
      # pull policies and setup qdrant before app
      pull_policies:
        condition: service_completed_successfully
    volumes:
      - ./app:/app # sync local and docker files for hot reload to take effect in flask debug mode
    ports:
      - 5000:5000 # expose port to host
    environment:
      - FLASK_DEBUG=1 # remove in release

  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports: # remove in release
      - 11434:11434 # expose port to host
    expose:
      - 11434 # expose port to other services only
    restart: always
    command: ["serve"]
    healthcheck:
      # ensure mistral is pulled with `docker exec ollama ollama pull mistral`
      # otherwise fail with 'container for service "ollama" is unhealthy'
      test: ["CMD", "ollama", "show", "--template", "mistral"]
      retries: 0
      timeout: 10s
    # -----------------------------
    # enable GPU support
    #environment:
    #  - gpus=all
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia # never tested anything but nvidia here..
    #          count: 1
    #          capabilities: [gpu]
    # -----------------------------

  qdrant_policies:
    container_name: qdrant_policies
    image: qdrant/qdrant
    volumes:
      - ./qdrant_policies:/root/.qdrant_policies
    ports: # remove in release
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    restart: always
    
  pull_policies:
    container_name: pull_policies
    build: ./pull_policies/
    depends_on:
      - qdrant_policies
    volumes:
      - ./qdrant_policies:/root/.qdrant_policies

volumes:
  app:
    name: app
  ollama:
    name: ollama
  qdrant_policies:
    name: qdrant_policies