version: '3.8'

services:
  app:
    container_name: app
    build: ./app/ # local source for backend
    depends_on:
      - ollama # build ollama before app
    volumes:
      - ./app:/app # sync local and docker files for hot reload to take effect in flask debug mode
    ports:
      - 5000:5000 # expose port to host
    environment:
      - FLASK_DEBUG=1 # remove in release

  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports: # remove in release
      - 11434:11434 # expose port to host
    expose:
      - 11434 # expose port to other services only
    command: ["serve"]
    # -----------------------------
    # enable GPU support
    #environment:
    #  - gpus=all
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia # never tested anything but nvidia here..
    #          count: 1
    #          capabilities: [gpu]
    # -----------------------------

volumes:
  ollama:
    name: ollama
  app:
    name: app